# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./globaldata.h \
    ./resource.h \
    ./CustomDataType.h \
    ./PactInformation.h \
    ./batteryplatform.h \
    ./smokingtestdialog.h \
    ./voltageaccuracytestdialog.h \
    ./batterywarnningdialog.h \
    ./currentaccuracytestdialog.h \
    ./Data_WriteTOExecl.h \
    ./chargetestdialog.h \
    ./dischargetestdialog.h \
    ./internalresistancedialog.h \
    ./processstatuswidget.h \
    ./message_box.h \
    ./testinstructhandle.h \
    ./selfdefinecheckwidget.h \
    ./verifywidget.h \
    ./dataanalyze.h \
    ./logsave.h \
    ./datareceive.h \
    ./mainreference.h \
    ./qcustomplot.h \
    ./chargeanddischargetest.h \
    ./capacitytestdialog.h
SOURCES += ./batteryplatform.cpp \
    ./batterywarnningdialog.cpp \
    ./chargetestdialog.cpp \
    ./currentaccuracytestdialog.cpp \
    ./dataanalyze.cpp \
    ./datareceive.cpp \
    ./Data_WriteTOExecl.cpp \
    ./dischargetestdialog.cpp \
    ./globaldata.cpp \
    ./internalresistancedialog.cpp \
    ./logsave.cpp \
    ./mainreference.cpp \
    ./message_box.cpp \
    ./PactInformation.cpp \
    ./processstatuswidget.cpp \
    ./qcustomplot.cpp \
    ./selfdefinecheckwidget.cpp \
    ./smokingtestdialog.cpp \
    ./testinstructhandle.cpp \
    ./verifywidget.cpp \
    ./voltageaccuracytestdialog.cpp \
    ./main.cpp \
    ./chargeanddischargetest.cpp \
    ./capacitytestdialog.cpp
FORMS += ./batterywarnningdialog.ui \
    ./chargetestdialog.ui \
    ./currentaccuracytestdialog.ui \
    ./batteryplatform.ui \
    ./dischargetestdialog.ui \
    ./internalresistancedialog.ui \
    ./mainreference.ui \
    ./message_box.ui \
    ./processstatuswidget.ui \
    ./selfdefinecheckwidget.ui \
    ./smokingtestdialog.ui \
    ./verifywidget.ui \
    ./voltageaccuracytestdialog.ui \
    ./chargeanddischargetest.ui \
    ./capacitytestdialog.ui
TRANSLATIONS += ./batteryplatform_zh.ts
RESOURCES += batteryplatform.qrc \
    Resource.qrc
