# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = BatteryPlatform
DESTDIR = ../Release
CONFIG += release
RC_ICONS = battery.ico
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(BatteryPlatform.pri)
TRANSLATIONS += batteryplatform_zh.ts
